jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: d17798d61b78b91a8abfca3e6f914fe5
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.233.145:55504/insider?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: insider
    password: ssafy
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://127.0.0.1:3306/gumiinsider?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
  #   username: ssafy
  #   password: ssafy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: InsiderApplication
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

mybatis:
  type-aliases-package: com.mygumi.insider.dto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.mygumi.insider: DEBUG

weather-key: uV/GNk/T5gti8n8xes/pFYKsJqLk1svJ2n5AwY09dD1GoHPGpY9dWHiOWCbK291n3WpYBuvklEP3323MYJUuaQ==
