
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gumiinsider?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://b0cc6db47f05f4:a1fdcaa0@us-cdbr-east-06.cleardb.net/heroku_0670d4891e0d708?reconnect=true
#    username: b0cc6db47f05f4
#    password: a1fdcaa0
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true



mybatis:
  type-aliases-package: com.mygumi.insider.dto
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.mygumi.insider: DEBUG

jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: d17798d61b78b91a8abfca3e6f914fe5
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com


weather-key: uV/GNk/T5gti8n8xes/pFYKsJqLk1svJ2n5AwY09dD1GoHPGpY9dWHiOWCbK291n3WpYBuvklEP3323MYJUuaQ==